# syntax=docker/dockerfile:1.7
ARG VERSION=dev

FROM golang:1.25-alpine AS builder

ARG VERSION

WORKDIR /build
COPY backend/go.mod backend/go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

COPY backend/ ./
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags "-s -w -X 'Wavelet/openflare/plugins/flared/config.Version=$VERSION'" -o flared ./cmd/flared/main.go

# Final runtime image
FROM fatedier/frpc:v0.69.0

WORKDIR /app

# Copy openflared binary
COPY --from=builder /build/flared .

ENV OPENFLARE_DATA_DIR=/app/data
ENV OPENFLARE_FRPC_PATH=/usr/bin/frpc

ENTRYPOINT ["/app/flared"]
CMD []
