apiVersion: apps/v1
kind: Deployment
metadata:
  name: wavelet
  labels:
    app: wavelet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wavelet
  template:
    metadata:
      labels:
        app: wavelet
    spec:
      containers:
        - name: wavelet
          image: wavelet
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http

